name: Build and Release Framework

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master ]
  release:
    types: [ created ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
        
    - name: Build with Maven
      run: mvn clean install -DskipTests
      
    - name: Upload JAR artifacts
      uses: actions/upload-artifact@v4
      with:
        name: framework-jars
        path: |
          target/*.jar
        retention-days: 30
        
    - name: Upload to GitHub Packages
      if: github.event_name == 'release'
      run: mvn deploy -DskipTests
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
