name: Publish to GitHub Packages

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    - name: Configure Maven settings
      run: |
        mkdir -p ~/.m2
        cat > ~/.m2/settings.xml << EOF
        <settings>
          <servers>
            <server>
              <id>github</id>
              <username>${{ github.actor }}</username>
              <password>${{ secrets.PAT_TOKEN || secrets.GH_TOKEN }}</password>
            </server>
          </servers>
        </settings>
        EOF

    - name: Publish to GitHub Packages
      run: mvn clean deploy -DskipTests -X
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN || secrets.GH_TOKEN }}
